<use f='include/llvm-7/llvm/Support/Error.h' l='1059' u='w' c='_ZN4llvm7ECError12setErrorCodeESt10error_code'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='1060' u='r' c='_ZNK4llvm7ECError18convertToErrorCodeEv'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='1061' u='m' c='_ZNK4llvm7ECError3logERNS_11raw_ostreamE'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='1068' u='w' c='_ZN4llvm7ECErrorC1ESt10error_code'/>
<dec f='include/llvm-7/llvm/Support/Error.h' l='1070' type='std::error_code'/>
<offset>64</offset>
