<dec f='include/llvm-7/llvm/Support/raw_ostream.h' l='478' type='std::string &amp;'/>
<use f='include/llvm-7/llvm/Support/raw_ostream.h' l='485' u='m' c='_ZNK4llvm18raw_string_ostream11current_posEv'/>
<use f='include/llvm-7/llvm/Support/raw_ostream.h' l='488' u='w' c='_ZN4llvm18raw_string_ostreamC1ERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='include/llvm-7/llvm/Support/raw_ostream.h' l='495' u='a' c='_ZN4llvm18raw_string_ostream3strB5cxx11Ev'/>
<offset>320</offset>
