<def f='codebrowser/generator/generator.h' l='40' ll='58'/>
<use f='codebrowser/generator/generator.h' l='45' c='_ZNK9Generator3TagltERKS0_'/>
<use f='codebrowser/generator/generator.h' l='52' c='_ZNK9Generator3TageqERKS0_'/>
<use f='codebrowser/generator/generator.h' l='60'/>
<use f='codebrowser/generator/generator.h' l='70' c='_ZN9Generator6addTagENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_ii'/>
<size>72</size>
<mbr r='Generator::Tag::name' o='0' t='std::string'/>
<mbr r='Generator::Tag::attributes' o='256' t='std::string'/>
<mbr r='Generator::Tag::pos' o='512' t='int'/>
<mbr r='Generator::Tag::len' o='544' t='int'/>
<fun r='_ZNK9Generator3TagltERKS0_'/>
<fun r='_ZNK9Generator3TageqERKS0_'/>
<fun r='_ZNK9Generator3Tag4openERN4llvm11raw_ostreamE'/>
<fun r='_ZNK9Generator3Tag5closeERN4llvm11raw_ostreamE'/>
<use f='codebrowser/generator/generator.cpp' l='224' c='_ZN9Generator8generateEN4llvm9StringRefENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS7_PKcSB_S1_S1_RKSt3setIS7_St4lessIS7_ESaIS7_EE'/>
<use f='codebrowser/generator/generator.cpp' l='231' c='_ZN9Generator8generateEN4llvm9StringRefENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS7_PKcSB_S1_S1_RKSt3setIS7_St4lessIS7_ESaIS7_EE'/>
<size>72</size>
<fun r='_ZNK9Generator3Tag4openERN4llvm11raw_ostreamE'/>
<fun r='_ZNK9Generator3Tag5closeERN4llvm11raw_ostreamE'/>
