<dec f='include/llvm-7/llvm/ADT/iterator.h' l='214' type='WrappedIteratorT'/>
<use f='include/llvm-7/llvm/ADT/iterator.h' l='218' u='w' c='_ZN4llvm21iterator_adaptor_baseC1ET0_'/>
<use f='include/llvm-7/llvm/ADT/iterator.h' l='223' u='a' c='_ZNK4llvm21iterator_adaptor_base7wrappedEv'/>
<use f='include/llvm-7/llvm/ADT/iterator.h' l='232' u='w' c='_ZN4llvm21iterator_adaptor_basepLET3_'/>
<use f='include/llvm-7/llvm/ADT/iterator.h' l='239' u='w' c='_ZN4llvm21iterator_adaptor_basemIET3_'/>
<use f='include/llvm-7/llvm/ADT/iterator.h' l='247' u='r' c='_ZNK4llvm21iterator_adaptor_basemiERKT_'/>
<use f='include/llvm-7/llvm/ADT/iterator.h' l='254' u='w' c='_ZN4llvm21iterator_adaptor_baseppEv'/>
<use f='include/llvm-7/llvm/ADT/iterator.h' l='262' u='w' c='_ZN4llvm21iterator_adaptor_basemmEv'/>
<use f='include/llvm-7/llvm/ADT/iterator.h' l='266' c='_ZNK4llvm21iterator_adaptor_baseeqERKT_'/>
<use f='include/llvm-7/llvm/ADT/iterator.h' l='271' c='_ZNK4llvm21iterator_adaptor_baseltERKT_'/>
<use f='include/llvm-7/llvm/ADT/iterator.h' l='274' u='r' c='_ZNK4llvm21iterator_adaptor_basedeEv'/>
