<use f='include/llvm-7/llvm/Pass.h' l='106' c='_ZN4llvm4Pass16doInitializationERNS_6ModuleE'/>
<use f='include/llvm-7/llvm/Pass.h' l='110' c='_ZN4llvm4Pass14doFinalizationERNS_6ModuleE'/>
<use f='include/llvm-7/llvm/Pass.h' l='118' c='_ZNK4llvm4Pass5printERNS_11raw_ostreamEPKNS_6ModuleE'/>
<use f='include/llvm-7/llvm/Pass.h' l='238' c='_ZN4llvm10ModulePass11runOnModuleERNS_6ModuleE'/>
<use f='include/llvm-7/llvm/Pass.h' l='248' c='_ZNK4llvm10ModulePass10skipModuleERNS_6ModuleE'/>
<use f='include/llvm-7/llvm/Pass.h' l='273' c='_ZN4llvm13ImmutablePass11runOnModuleERNS_6ModuleE'/>
<use f='include/llvm-7/llvm/IR/DataLayout.h' l='191' c='_ZN4llvm10DataLayoutC1EPKNS_6ModuleE'/>
<use f='include/llvm-7/llvm/IR/DataLayout.h' l='215' c='_ZN4llvm10DataLayout4initEPKNS_6ModuleE'/>
