<dec f='include/llvm-7/llvm/Support/raw_ostream.h' l='505' type='SmallVectorImpl&lt;char&gt; &amp;'/>
<use f='include/llvm-7/llvm/Support/raw_ostream.h' l='520' u='w' c='_ZN4llvm19raw_svector_ostreamC1ERNS_15SmallVectorImplIcEE'/>
<use f='include/llvm-7/llvm/Support/raw_ostream.h' l='529' u='m' c='_ZN4llvm19raw_svector_ostream3strEv'/>
<use f='include/llvm-7/llvm/Support/raw_ostream.h' l='529' u='m' c='_ZN4llvm19raw_svector_ostream3strEv'/>
<offset>320</offset>
