<use f='include/llvm-7/llvm/Support/Error.h' l='1118' u='a' c='_ZNK4llvm11StringError10getMessageB5cxx11Ev'/>
<dec f='include/llvm-7/llvm/Support/Error.h' l='1121' type='std::string'/>
<offset>64</offset>
